### ISSUE TITLE
在SwaggerFilter中抛出了ClassNotFoundException

### ISSUE THREAD

**Issue by DevilHeS** [tminglei/binder-swagger-java#4]
当程序运行到这里时
![c fnhqres01h5 9velx](https://cloud.githubusercontent.com/assets/7010685/20045842/4a4a5f9a-a4df-11e6-9c55-5b65d3d809dc.png)

clz的格式大概是

>  “com/xxx/xxx”  

就会抛出 ClassNotFoundException ， 然后我在

> Class.forName(clz);

之前添加了

> clz = clz.replaceAll("/", ".");
                            clz = clz.replaceAll("\\\\", ".");

这样就一切正常了！

我不知道 你本意就是把路径变成  xxx/xxx 这样的格式， 还是这是一个疏漏

**Comment by tminglei** [comment]
奇怪，实例项目直接用它跑的，没有问题啊。
当然我用的是 linux，你是 windows 吧？

**Comment by DevilHeS** [comment]
是在windows上的

**Comment by tminglei** [comment]
嗯，看来我要在 windows 也测一下

**Comment by tminglei** [comment]
Fix 了，你帮忙多检查一下。没有问题的话我就发一个补丁版本。

**Comment by DevilHeS** [comment]
在我这里测试了一下没问题

**Comment by tminglei** [comment]
发布了 0.6.2 版，请更新使用。
